### PR TITLE
Workon windows

### PR DESCRIPTION
**Pull request by zodman**
http://puu.sh/hwDhH/f356be6fc5.jpg

### CODE REVIEW

**Comment by felipelerena** [comment]
Looks OK, just trying to find out if the daemon change does not break the tsproxy backend in Linux

**Comment by felipelerena** [comment]
Sorry buy your patch makes lots of core changes that breake half of the functionality (you broke tsproxy which is like a very core feature)
It also make unsolicited architecture changes like unsing tempfile for the lockfile which not only doesn't work is also pointless.

I really want touchandgo working on Windows... But we can't break linux in the process.

**Comment by felipelerena** [comment]
Are you fisically in Buenos Aires? maybe we can get together with @gilgamezh and find a way to make it work

**Comment by zodman** [comment]
we can make a irc pair programming or something

**Comment by felipelerena** [comment]
Yeah, sure.

**Comment by zodman** [comment]
close plz!

**Pull request closed without merging**
